import type { Metadata } from "next";

import "./globals.css";

import ContextWrapper from "./components/ui/context-wrapper";


export const metadata: Metadata = {
  title: "HRM - Quoc Bao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextWrapper>{children}</ContextWrapper>
    </html>
  );
}
